

FEWTANHS_DEFAULT_PARAMS = [dict(mean_fading_factor=0.1,
                                var_fading_factor=0.01,
                                outlier_fading_factor=0.3,
                                alpha=0.2),
                           dict(mean_fading_factor=0.2,
                                var_fading_factor=0.01,
                                outlier_fading_factor=0.3,
                                alpha=0.2),
                          dict(mean_fading_factor=0.3,
                                var_fading_factor=0.01,
                                outlier_fading_factor=0.3,
                                alpha=0.2),
                          dict(mean_fading_factor=0.4,
                                var_fading_factor=0.01,
                                outlier_fading_factor=0.3,
                                alpha=0.2),
                          dict(mean_fading_factor=0.1,
                                var_fading_factor=0.01,
                                outlier_fading_factor=0.1,
                                alpha=0.2),
                            dict(mean_fading_factor=0.1,
                                var_fading_factor=0.01,
                                outlier_fading_factor=0.3,
                                alpha=0.1)]
